---
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PHOENIX_COLLECTOR_ENDPOINT=http://phoenix:6006
      - PYTHONUNBUFFERED=1
    depends_on:
      - ollama
    networks:
      - rag-network
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    # command: >
    #   ollama run llama3.2:3b
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - rag-network
    post_start:
      - command : "ollama run llama3.2:3b"
    restart: unless-stopped

  phoenix:
    image: arizephoenix/phoenix:latest
    ports:
      - "6006:6006"
      - "4317:4317"
    # command: phoenix serve
    networks:
      - rag-network
    restart: unless-stopped

volumes:
  ollama-data:


networks:
  rag-network:
    driver: bridge